"""add_auth_championship

Revision ID: 4e09b9eab350
Revises: e83073e64a91
Create Date: 2026-07-25 01:01:50.372652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision = '4e09b9eab350'
down_revision = 'e83073e64a91'
branch_labels = None
depends_on = None


def upgrade():
    # Clean up existing transient data before schema changes
    op.execute("DELETE FROM `match`")
    op.execute("DELETE FROM group_participant")
    op.execute("DELETE FROM `group`")
    op.execute("DELETE FROM participant")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('championship',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('status', sa.Enum('draft', 'games', 'complete', name='championship_status'), nullable=False),
    sa.Column('budget_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_account',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('oauth_name', sa.String(length=100), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=False),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('account_id', sa.String(length=320), nullable=False),
    sa.Column('account_email', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)
    op.create_table('draft_pick',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('group', sa.Column('championship_id', sa.Integer(), nullable=False))
    op.alter_column('group', 'name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'group', 'championship', ['championship_id'], ['id'], ondelete='CASCADE')
    op.alter_column('match', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('match', 'round',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('nation', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=False)
    op.add_column('participant', sa.Column('team_name', sa.String(length=255), nullable=True))
    op.add_column('participant', sa.Column('championship_id', sa.Integer(), nullable=False))
    op.alter_column('participant', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_foreign_key(None, 'participant', 'championship', ['championship_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'participant', 'team', ['team_name'], ['name'], ondelete='SET NULL')
    op.alter_column('player', 'position_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'team_origin',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('player', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('player', 'nation',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('player', 'specific_position',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               nullable=False)
    op.alter_column('player', 'overall',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'pace',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'shooting',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'passing',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'dribbling',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'defending',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'physical',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('player', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=False)
    op.create_foreign_key(None, 'player', 'team', ['team_origin'], ['name'])
    op.create_foreign_key(None, 'player', 'nation', ['nation'], ['name'])
    op.create_foreign_key(None, 'player', 'position', ['position_id'], ['id'])
    op.alter_column('position', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('position', 'specific_positions',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('team', 'image_path',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=False)
    op.drop_constraint('team_ibfk_1', 'team', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('team_ibfk_1', 'team', 'participant', ['participant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('team', 'image_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('position', 'specific_positions',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('position', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.alter_column('player', 'image_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('player', 'physical',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'defending',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'dribbling',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'passing',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'shooting',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'pace',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'overall',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('player', 'specific_position',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('player', 'nation',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('player', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('player', 'team_origin',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('player', 'position_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.drop_constraint(None, 'participant', type_='foreignkey')
    op.alter_column('participant', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('participant', 'championship_id')
    op.drop_column('participant', 'team_name')
    op.alter_column('nation', 'image_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('match', 'round',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('match', 'group_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.alter_column('group', 'name',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('group', 'championship_id')
    op.drop_table('draft_pick')
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.drop_table('oauth_account')
    op.drop_table('championship')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
