# Generated by Django 3.2.6 on 2022-07-29 12:37

from django.db import migrations
import json

def insert_positions(apps, schema_editor):
  Position = apps.get_model('WebApp', 'Position')
  for position in Position.objects.all():
    position.delete()

  f = open('data/positions.json')
  data = json.load(f)

  for position in data:
    position = Position(id = position['id'], name = position['name'], specific_positions = position['specific_positions'])
    position.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20220313_1129'),
    ]

    operations = [
      migrations.RunPython(insert_positions)
    ]
