# Generated by Django 3.2.6 on 2022-07-29 13:05

from django.db import migrations
import json

def insert_nations(apps, schema_editor):
  Nation = apps.get_model('WebApp', 'Nation')
  for nation in Nation.objects.all():
    nation.delete()

  f = open('data/nations.json')
  data = json.load(f)

  for nation in data:
    nation = Nation(id = nation['id'], name = nation['name'], image_path = nation['image_path'])
    nation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_fill_positions'),
    ]

    operations = [
      migrations.RunPython(insert_nations)
    ]
