# Generated by Django 3.2.6 on 2022-07-29 13:10

from django.db import migrations
import json

def insert_teams(apps, schema_editor):
  Team = apps.get_model('WebApp', 'Team')
  for team in Team.objects.all():
    team.delete()

  f = open('data/teams.json')
  data = json.load(f)

  for team in data:
    team = Team(id = team['id'], name = team['name'], image_path = team['image_path'])
    team.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_fill_nations'),
    ]

    operations = [
      migrations.RunPython(insert_teams)
    ]
