# Generated by Django 3.2.6 on 2022-07-29 13:24

from django.db import migrations
import json

def insert_players(apps, schema_editor):
  Player = apps.get_model('WebApp', 'Player')
  Nation = apps.get_model('WebApp', 'Nation')
  Position = apps.get_model('WebApp', 'Position')
  Team = apps.get_model('WebApp', 'Team')

  for player in Player.objects.all():
    player.delete()

  f = open('data/players.json')
  data = json.load(f)

  for player in data:
    position = Position.objects.get(id = player['position'])
    team = Team.objects.get(id = player['team_origin'])
    nation = Nation.objects.get(id = player['nation'])
    player = Player(id = player['id'], name = player['name'], image_path = player['image_path'], 
                    team_origin = team, nation = nation, position = position,
                    specific_position = player['specific_position'], overall = player['overall'], 
                    pace = player['pace'], shooting = player['shooting'], passing = player['passing'], 
                    dribbling = player['dribbling'], defending = player['defending'], physical = player['physical'])
    player.save()


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_fill_teams'),
    ]

    operations = [
      migrations.RunPython(insert_players)
    ]
