# Generated by Django 3.2.6 on 2022-07-29 14:30

from django.db import migrations
import json

def address_teams_leagues(apps, schema_editor):
  League = apps.get_model('WebApp', 'League')
  Team = apps.get_model('WebApp', 'Team')

  f = open('data/leagues.json', encoding='utf-8')
  data = json.load(f)

  for key, values in data.items():
    league = League.objects.get(name = key)
    for team_name in values:
      try:
        team = Team.objects.get(name = team_name)
        team.league = league
        team.save()
      except:
        continue


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_fill_leagues'),
    ]

    operations = [
      migrations.RunPython(address_teams_leagues)
    ]
