# Generated by Django 3.0.2 on 2020-05-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_auto_20200508_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='goals_team_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='goals_team_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Group'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_1', to='WebApp.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_2', to='WebApp.Team'),
        ),
    ]
