# Generated by Django 3.0.2 on 2020-05-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_auto_20200508_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='defending',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='dribbling',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='pace',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='passing',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='physical',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='shooting',
            field=models.IntegerField(null=True),
        ),
    ]
