# Generated by Django 3.0.2 on 2020-05-09 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_auto_20200509_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='nation',
        ),
    ]
