# Generated by Django 3.0.2 on 2020-05-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_remove_league_nation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='WebApp.Position'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_origin', to='WebApp.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_participant', to='WebApp.Team'),
        ),
    ]
