# Generated by Django 3.0.2 on 2020-05-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_auto_20200509_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='image_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image_link',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='known_as',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image_link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
