# Generated by Django 3.0.2 on 2020-05-27 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_auto_20200527_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='known_as',
        ),
    ]
