# Generated by Django 3.0.2 on 2020-05-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_remove_player_known_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='specific_position',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
