# Generated by Django 3.0.2 on 2020-06-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_player_specific_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
