# Generated by Django 3.0.2 on 2020-06-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0011_player_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
