# Generated by Django 3.2.6 on 2022-01-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_auto_20200608_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='specific_positions',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
